name: tests unitaires
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: installation pytest
        run: apt install python3-pytest 
      - name: Run tests
        run: pytest /test.py

